[project]
name = "image-downloader"
version = "0.1.0"
description = "Image downloader service"
requires-python = ">=3.14"
dependencies = [
    "aio-pika>=9.5.8",
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.2",
    "tqdm>=4.67.1",
]
